export const data = [
  {
    id: 1,
    price: 22,
    disount: "5%",
    count: 0,
    seller: "Nike IIII",
    name: "nike T-shirt men",
    url: "https://www.mdtextile.com/images/stories/virtuemart/product/foursquare-160gsm-roundneck-darkmelange-tshirt.jpg",
  },
  {
    id: 2,
    count: 0,
    seller: "Puma",
    price: 44.99,
    disount: "15%",
    name: "Puma T-shirt female",
    url: "https://www.mdtextile.com/images/stories/virtuemart/product/foursquare-160gsm-roundneck-darkmelange-tshirt.jpg",
  },
  {
    id: 3,
    count: 0,
    seller: "Adidas",
    price: 40,
    name: "Adidas T-shirt female",
    url: "https://www.mdtextile.com/images/stories/virtuemart/product/foursquare-160gsm-roundneck-darkmelange-tshirt.jpg",
  },
  {
    id: 4,
    count: 0,
    seller: "CK",
    price: 50,
    name: "CK T-shirt kids",
    url: "https://www.mdtextile.com/images/stories/virtuemart/product/foursquare-160gsm-roundneck-darkmelange-tshirt.jpg",
  },
];
